@domain = http://localhost:3001

###
POST {{domain}}/user/register
Content-Type: application/json

{
    "name": "Alejandro",
    "username": "alejandro5",
    "email": "alejandro@gmail.com",
    "password": "123456",
    "role": "admin"
}

###
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "alejandro@gmail.com",
    "password": "123456"
}