@domain = http://localhost:3001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc5MzQxMzM1YTA0NjIxOWRjNTE5MDgiLCJuYW1lIjoiRGFuaWVsIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzUyNzczNjUyLCJleHAiOjE3NTI3ODA4NTJ9.2kibsY8Xa0u6VBoAf5FpVMdYDghFeVl2klp7avR5uEk


###
POST {{domain}}/user/register
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@gmail.com",
    "password": "123456",
    "role": "customer"
}

###
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "alejandro@gmail.com",
    "password": "123456"
}
###
GET  {{domain}}/user/me
Authorization: Bearer {{token}}

###
POST {{domain}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Pizza margarita",
    "description": "Pizza tradicional con salsa de tomate, mozzarella y albahaca",
    "price": 8,
    "category": "Pizza",
    "imageUrl": "https://www.grupoestrellapolar.com/files/products/pizza_margarita1.png",
    "available": "true"
}
###
PUT {{domain}}/products/687933da35a046219dc51903
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "price": 9
}

###
DELETE {{domain}}/products/687781b7586c7edcea7f69fb
Content-Type: application/json
Authorization: Bearer {{token}}