@domain = http://localhost:3001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODc1ODEzZDk1YTcwODBjM2M0NWRjZGYiLCJuYW1lIjoiQWxlamFuZHJvIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUyOTE5OTUzLCJleHAiOjE3NTI5MjcxNTN9.t7OKe2msq9PTmXGYFW9442Ab7j5rR6JvHPWn-49Bry4


###
POST {{domain}}/user/register
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@gmail.com",
    "password": "123456",
    "role": "customer"
}

###
POST {{domain}}/user/login
Content-Type: application/json

{
    "email": "alejandro@gmail.com",
    "password": "123456"
}
###
GET  {{domain}}/user/me
Authorization: Bearer {{token}}

###
POST {{domain}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Raviolis carbonara",
    "description": "Raviolis rellenos de queso y jamón, bañados en cremosa salsa carbonara con panceta",
    "price": 10,
    "category": "Pasta",
    "imageUrl": "https://www.pamperedchef.com/iceberg/com/recipe/32017-lg.jpg",
    "available": "true"
}
###
PUT {{domain}}/products/687933da35a046219dc51903
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "price": 9
}

###
DELETE {{domain}}/products/687781b7586c7edcea7f69fb
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{domain}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "products": [
    {
      "id": "687b7429533a4ac2d9d16ba7",
      "quantity": 1
    },
    {
      "id": "687933da35a046219dc51903",
      "quantity": 1
    }
  ],
  "deliveryAddress": "Calle Falsa 123, Springfield"
}
